### ISSUE TITLE
deplop:wp:core can not be called after "deploy:symlink" 

### ISSUE THREAD

**Issue by MalikZohaib** [sourcebroker/deployer-extended-wordpress#4] opened 2018-08-20 15:55 UTC
I have tried many time to deploy using this but i got this error. I have setup everything correctly on my local.
![image](https://user-images.githubusercontent.com/12460091/44351450-55324e80-a4bb-11e8-91e5-9bf89c8f992e.png)

**Comment by kszymukowicz** [comment] 2018-08-20 21:00
Please show full log from "dep deploy live -vvv".

**Comment by MalikZohaib** [comment] 2018-08-28 12:05
Here is the full log 
➤ Executing task deploy:check_lock
• done on [live]
✔ Ok [1ms]
➤ Executing task deploy:check_composer_install
[localhost] > : which composer
> /usr/local/bin/composer
[localhost] > : which php
> /usr/bin/php
[localhost] > : /usr/bin/php /usr/local/bin/composer --ignore-platform-reqs install --dry-run 2>&1
> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_curl.dll' - /usr/lib/php/20151012/php_curl.dll: cannot open shared object file: No such file or directory in Unknown on line 0
> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_curl.dll' - /usr/lib/php/20151012/php_curl.dll: cannot open shared object file: No such file or directory in Unknown on line 0
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
• done on [live]
✔ Ok [511ms]
➤ Executing task deploy:prepare
[live] > echo $0
  SSH multiplexing initialization
Warning: the ECDSA host key for 'sourcebroker.gj.com.pk' differs from the key for the IP address '185.135.156.234'
Offending key for IP in /home/vagrant/.ssh/known_hosts:5
Matching host key in /home/vagrant/.ssh/known_hosts:33
Are you sure you want to continue connecting (yes/no)? yes
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[live] < bash
[live] > if [ ! -d ~/../../web ]; then mkdir -p ~/../../web; fi
[live] > if [ ! -L ~/../../web/current ] && [ -d ~/../../web/current ]; then echo true; fi
[live] > cd ~/../../web && if [ ! -d .dep ]; then mkdir .dep; fi
[live] > cd ~/../../web && if [ ! -d releases ]; then mkdir releases; fi
[live] > cd ~/../../web && if [ ! -d shared ]; then mkdir shared; fi
• done on [live]
✔ Ok [12s 220ms]
➤ Executing task deploy:lock
[live] > if [ -f ~/../../web/.dep/deploy.lock ]; then echo 'true'; fi
[live] > touch ~/../../web/.dep/deploy.lock
• done on [live]
✔ Ok [1s 444ms]
➤ Executing task deploy:release
[live] > cd ~/../../web && (if [ -h release ]; then echo 'true'; fi)
[live] > cd ~/../../web && ([ -d releases ] && [ "$(ls -A releases)" ] && echo "true" || echo "false")
[live] < true
[live] > cd ~/../../web && (cd releases && ls -t -1 -d */)
[live] < 11/
[live] < 12/
[live] < 10/
[live] < 9/
[live] < 8/
[live] > cd ~/../../web && (if [ -f .dep/releases ]; then echo "true"; fi)
[live] < true
[live] > cd ~/../../web && (tail -n 15 .dep/releases)
[live] < 20180820213251,4
[live] < 20180820214026,5
[live] < 20180820214203,5
[live] < 20180820215023,6
[live] < 20180821085528,7
[live] < 20180821085950,7
[live] < 20180821090358,7
[live] < 20180821090628,7
[live] < 20180821090958,7
[live] < 20180821091835,7
[live] < 20180821092655,8
[live] < 20180821094016,9
[live] < 20180821094830,10
[live] < 20180827084303,11
[live] < 20180827091837,12
[live] > cd ~/../../web && (if [ -d ~/../../web/releases/13 ]; then echo 'true'; fi)
[live] > cd ~/../../web && (date +"%Y%m%d%H%M%S")
[live] < 20180828140316
[live] > cd ~/../../web && (echo '20180828140316,13' >> .dep/releases)
[live] > cd ~/../../web && (mkdir ~/../../web/releases/13)
[live] > cd ~/../../web && (if [[ "$(man ln)" =~ "--relative" ]]; then echo "true"; fi)
[live] < true
[live] > cd ~/../../web && (ln -nfs --relative ~/../../web/releases/13 ~/../../web/release)
• done on [live]
✔ Ok [9s 791ms]
➤ Executing task deploy:update_code
[live] > which git
[live] < /usr/bin/git
[live] > /usr/bin/git version
[live] < git version 2.11.0
[live] > if [ -h ~/../../web/release ]; then echo 'true'; fi
[live] < true
[live] > readlink ~/../../web/release
[live] < releases/13
[live] > /usr/bin/git clone  --recursive -q --reference ~/../../web/releases/11 --dissociate https://gitium:zkEfmoShgatzS2Wxi3LE@gitlab.gosign.io/zohaib/sourcebroker.git  ~/../../web/releases/13 2>&1
[live] > /usr/bin/git clone  --recursive -q https://gitium:zkEfmoShgatzS2Wxi3LE@gitlab.gosign.io/zohaib/sourcebroker.git ~/../../web/releases/13 2>&1
[live] < /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
• done on [live]
✔ Ok [6s 546ms]
➤ Executing task deploy:shared
[live] > if [ -d ~/../../web/shared/wp-content/uploads ]; then echo 'true'; fi
[live] < true
[live] > rm -rf ~/../../web/releases/13/wp-content/uploads
[live] > mkdir -p `dirname ~/../../web/releases/13/wp-content/uploads`
[live] > ln -nfs --relative ~/../../web/shared/wp-content/uploads ~/../../web/releases/13/wp-content/uploads
[live] > if [ -d ~/../../web/shared/wp-content/languages ]; then echo 'true'; fi
[live] < true
[live] > rm -rf ~/../../web/releases/13/wp-content/languages
[live] > mkdir -p `dirname ~/../../web/releases/13/wp-content/languages`
[live] > ln -nfs --relative ~/../../web/shared/wp-content/languages ~/../../web/releases/13/wp-content/languages
[live] > if [ -d ~/../../web/shared/wp-content/upgrade ]; then echo 'true'; fi
[live] < true
[live] > rm -rf ~/../../web/releases/13/wp-content/upgrade
[live] > mkdir -p `dirname ~/../../web/releases/13/wp-content/upgrade`
[live] > ln -nfs --relative ~/../../web/shared/wp-content/upgrade ~/../../web/releases/13/wp-content/upgrade
[live] > if [ -f $(echo ~/../../web/releases/13/wp-config-local.php) ]; then rm -rf ~/../../web/releases/13/wp-config-local.php; fi
[live] > if [ ! -d $(echo ~/../../web/releases/13/.) ]; then mkdir -p ~/../../web/releases/13/.;fi
[live] > mkdir -p ~/../../web/shared/.
[live] > touch ~/../../web/shared/wp-config-local.php
[live] > ln -nfs --relative ~/../../web/shared/wp-config-local.php ~/../../web/releases/13/wp-config-local.php
• done on [live]
✔ Ok [12s 727ms]
➤ Executing task deploy:writable
[live] > ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1
[live] < www-data
[live] > cd ~/../../web/releases/13 && (mkdir -p wp-content/uploads wp-content/plugins wp-content/languages wp-content/upgrade)
[live] > cd ~/../../web/releases/13 && (chmod 2>&1; true)
[live] < chmod: missing operand
[live] < Try 'chmod --help' for more information.
[live] > cd ~/../../web/releases/13 && (if hash setfacl 2>/dev/null; then echo 'true'; fi)
[live] < true
[live] > cd ~/../../web/releases/13 && (getfacl -p wp-content/uploads | grep "^user:www-data:.*w" | wc -l)
[live] < 1
[live] > cd ~/../../web/releases/13 && (getfacl -p wp-content/plugins | grep "^user:www-data:.*w" | wc -l)
[live] < 0
[live] > cd ~/../../web/releases/13 && (setfacl -RL -m u:"www-data":rwX -m u:`whoami`:rwX wp-content/plugins)
[live] > cd ~/../../web/releases/13 && (setfacl -dRL -m u:"www-data":rwX -m u:`whoami`:rwX wp-content/plugins)
[live] > cd ~/../../web/releases/13 && (getfacl -p wp-content/languages | grep "^user:www-data:.*w" | wc -l)
[live] < 1
[live] > cd ~/../../web/releases/13 && (getfacl -p wp-content/upgrade | grep "^user:www-data:.*w" | wc -l)
[live] < 1
• done on [live]
✔ Ok [7s 422ms]
➤ Executing task deploy:vendors
[live] > if hash composer 2>/dev/null; then echo 'true'; fi
[live] < true
[live] > which composer
[live] < /usr/local/bin/composer
[live] > which php
[live] < /usr/bin/php
[live] > cd ~/../../web/releases/13 &&  /usr/bin/php /usr/local/bin/composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader
• done on [live]
✔ Ok [6s 344ms]
➤ Executing task deploy:wp:core
[live] > if [ -h '~/../../web/release' ]; then echo 'true'; fi
➤ Executing task deploy:failed
• done on [live]
✔ Ok [0ms]


  [RuntimeException]
  Task "deploy:wp:core" can not be called after "deploy:symlink" [Error code: 1827354672]


Exception trace:
 () at /var/www/wpstructure-extended/vendor/sourcebroker/deployer-extended-wordpress/deployer/deploy/task/deploy:wp:core.php:16
 SourceBroker\DeployerLoader\Utility\FileUtility->Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/bin/dep/src/Task/Task.php:85
 Deployer\Task\Task->run() at phar:///usr/bin/dep/src/Executor/SeriesExecutor.php:40
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/bin/dep/src/Console/TaskCommand.php:103
 Deployer\Console\TaskCommand->execute() at phar:///usr/bin/dep/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/dep/vendor/symfony/console/Application.php:869
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/dep/src/Console/Application.php:123
 Deployer\Console\Application->doRunCommand() at phar:///usr/bin/dep/vendor/symfony/console/Application.php:223
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/dep/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at phar:///usr/bin/dep/src/Deployer.php:194
 Deployer\Deployer->run() at phar:///usr/bin/dep/bin/dep:119
 require() at /usr/bin/dep:4

deploy [-p|--parallel] [--no-hooks]

**Comment by MalikZohaib** [comment] 2018-09-02 10:38
<?php
namespace Deployer;
set('repository', 'gitlab.example.coom/zohaib/sourcebroker.git');

server('live', 'sourcebroker.as46.de')
    ->user('gosignsourcebroker46')
    ->set('public_urls', ['https://sourcebroker.as46.de/'])
    ->set('deploy_path', '~/../../web');

**Comment by MalikZohaib** [comment] 2018-09-02 10:46
I changed this line of code in my extended file 
https://github.com/sourcebroker/deployer-extended-wordpress/blob/master/deployer/deploy/task/deploy:wp:core.php#L15
to this 
`if (!test("[ -h {{deploy_path}}/release ]")) {
        throw new \RuntimeException('Task "deploy:wp:core" can not be called after "deploy:symlink" [Error code: 1827354672]');
    }`
now its working fine

**Comment by kszymukowicz** [comment] 2018-09-02 10:55
The problem is because you used "~" for homepage. "~" is not working in single apostrophe. This is a bug. I will fix it next days probably.

**Comment by MalikZohaib** [comment] 2018-09-02 10:59
ok that will be great

**Comment by kszymukowicz** [comment] 2020-08-29 19:05
Late but finally fixed in 2.0.2 : )

**Closed by kszymukowicz** 2020-08-29 19:05 UTC
